apiVersion: v1
kind: Service
metadata:
  labels:
    name: sonar
  name: sonar
spec:
  ports:
    - port: 80
      targetPort: 8080
      name: sonarport
  selector:
    name: sonar
  type: LoadBalancer